steps:
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/vidya-ai", "."]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/vidya-ai"]
options:
  logging: CLOUD_LOGGING_ONLY
images:
  - "gcr.io/$PROJECT_ID/vidya-ai"
