steps:
  # Build and push the Docker image (using multi-stage build)
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/vidya-ai", "."]

  # Push the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/vidya-ai"]

# Specify logging configuration
options:
  logging: CLOUD_LOGGING_ONLY # Only write logs to Cloud Logging
  machineType: "E2_HIGHCPU_8"

# Specify the logs bucket
logsBucket: "gs://vidya-ai-build-logs-20240803"

images:
  - "gcr.io/$PROJECT_ID/vidya-ai"
