steps:
  # Install dependencies with dev dependencies included
  - name: "gcr.io/cloud-builders/npm"
    args: ["install", "--include=dev"]
    env:
      - "NODE_ENV=development"

  # Verify TypeScript is installed
  - name: "gcr.io/cloud-builders/npm"
    args: ["list", "typescript"]

  # Build the Next.js application
  - name: "gcr.io/cloud-builders/npm"
    args: ["run", "build"]
    env:
      - "NODE_ENV=production"
      - "NEXT_TELEMETRY_DISABLED=1"

  # Build the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/vidya-ai", "."]

  # Push the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/vidya-ai"]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - "gcr.io/$PROJECT_ID/vidya-ai"
