steps:
  # Pull the Node.js 20.19.4 image explicitly
  - name: "gcr.io/cloud-builders/docker"
    args: ["pull", "node:20.19.4-slim"]

  # Build the application
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--no-cache",
        "--build-arg",
        "NODE_ENV=production",
        "--build-arg",
        "NEXT_TELEMETRY_DISABLED=1",
        "-t",
        "gcr.io/$PROJECT_ID/vidya-ai",
        ".",
      ]
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/vidya-ai"]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

images:
  - "gcr.io/$PROJECT_ID/vidya-ai"
