steps:
  # Step 1: Build and push the Docker image (using multi-stage build in Dockerfile)
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--build-arg",
        "NEXT_DISABLE_LIGHTNINGCSS=1",
        "-t",
        "gcr.io/$PROJECT_ID/vidya-ai",
        ".",
      ]

  # Step 2: Push the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/vidya-ai"]

# Specify logging configuration
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"

images:
  - "gcr.io/$PROJECT_ID/vidya-ai"
