steps:
  # Step 1: Build the Docker image using minimal configuration
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "--platform",
        "linux/amd64",
        "-f",
        "Dockerfile",
        "-t",
        "gcr.io/$PROJECT_ID/vidya-ai",
        ".",
      ]

  # Step 2: Push the Docker image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/vidya-ai"]

# Specify build options
options:
  machineType: "E2_HIGHCPU_8"
  logging: CLOUD_LOGGING_ONLY

images:
  - "gcr.io/$PROJECT_ID/vidya-ai"
