steps:
  # Use Node.js 20.x builder
  - name: "node:20.19.4"
    entrypoint: npm
    args: ["install"]
    env:
      - "NODE_ENV=development"

  # Install TypeScript globally
  - name: "node:20.19.4"
    entrypoint: npm
    args: ["install", "-g", "typescript@5"]

  # Build the application
  - name: "node:20.19.4"
    entrypoint: npm
    args: ["run", "build"]
    env:
      - "NODE_ENV=production"
      - "NEXT_TELEMETRY_DISABLED=1"

  # Build the container
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/vidya-ai", "."]

  # Push the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/vidya-ai"]

options:
  logging: CLOUD_LOGGING_ONLY
  machineType: "E2_HIGHCPU_8"
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

images:
  - "gcr.io/$PROJECT_ID/vidya-ai"
