name: deploy-demo-fixed
description: Build and deploy to Cloud Run service vidya-ai-github-io on push to main
github:
  owner: vidya-ai-032
  name: vidya-ai-github.io
  push:
    branch: ^main$
build:
  steps:
  - name: gcr.io/cloud-builders/docker
    args:
    - build
    - --platform
    - linux/amd64
    - -f
    - Dockerfile
    - -t
    - gcr.io/$PROJECT_ID/vidya-ai
    - .
  - name: gcr.io/cloud-builders/docker
    args:
    - push
    - gcr.io/$PROJECT_ID/vidya-ai
  options:
    machineType: E2_HIGHCPU_8
  images:
  - gcr.io/$PROJECT_ID/vidya-ai 